from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_feedback(object):
    def setupUi(self, add_feedback):
        add_feedback.setObjectName("add_feedback")
        add_feedback.resize(1140, 850)
        self.back_btn = QtWidgets.QPushButton(add_feedback)
        self.back_btn.setGeometry(QtCore.QRect(930, 100, 181, 71))
        self.back_btn.setStyleSheet("QPushButton{\n""background-color: rgb(255, 255, 255);\n"
                                    "font: 63 20pt \"Yu Gothic UI Semibold\";\n""border-radius: 30;\n""}\n""\n"
                                    "QPushButton:pressed{\n""    background-color: rgb(200, 200, 200)\n""    \n""}")
        self.back_btn.setObjectName("back_btn")
        self.green_l = QtWidgets.QLabel(add_feedback)
        self.green_l.setGeometry(QtCore.QRect(0, 0, 1141, 81))
        self.green_l.setStyleSheet("background-color: rgb(0, 85, 0);")
        self.green_l.setText("")
        self.green_l.setObjectName("green_l")
        self.mainl2 = QtWidgets.QLabel(add_feedback)
        self.mainl2.setGeometry(QtCore.QRect(170, 10, 201, 61))
        self.mainl2.setMaximumSize(QtCore.QSize(201, 16777215))
        font = QtGui.QFont()
        font.setFamily("Adobe Caslon Pro")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.mainl2.setFont(font)
        self.mainl2.setStyleSheet("background-color: rgb(0, 85, 0);\n""color: rgb(217, 217, 217);")
        self.mainl2.setObjectName("mainl2")
        self.mainl = QtWidgets.QLabel(add_feedback)
        self.mainl.setGeometry(QtCore.QRect(10, 10, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe Caslon Pro")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.mainl.setFont(font)
        self.mainl.setStyleSheet("background-color: rgb(0, 85, 0);\n""\n""font: 20pt \"Adobe Caslon Pro\";\n"
                                 "color: rgb(255, 255, 255);")
        self.mainl.setObjectName("mainl")
        self.black_l = QtWidgets.QLabel(add_feedback)
        self.black_l.setGeometry(QtCore.QRect(0, 80, 1141, 101))
        self.black_l.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.black_l.setText("")
        self.black_l.setObjectName("black_l")
        self.add_feedback_2 = QtWidgets.QLabel(add_feedback)
        self.add_feedback_2.setGeometry(QtCore.QRect(310, 50, 741, 131))
        self.add_feedback_2.setStyleSheet("font: 63 40pt \"Yu Gothic UI Semibold\";\n""color: rgb(255, 255, 255);\n""")
        self.add_feedback_2.setObjectName("add_feedback_2")
        self.picture1 = QtWidgets.QLabel(add_feedback)
        self.picture1.setGeometry(QtCore.QRect(-260, 620, 551, 511))
        self.picture1.setText("")
        self.picture1.setPixmap(QtGui.QPixmap("./pictures/oak_tree01.jpgE551438F-166F-491C-AE90-13DCE18C6367Large.jpg"))
        self.picture1.setObjectName("picture1")
        self.picture2 = QtWidgets.QLabel(add_feedback)
        self.picture2.setGeometry(QtCore.QRect(760, 630, 551, 511))
        self.picture2.setText("")
        self.picture2.setPixmap(QtGui.QPixmap("./pictures/oak_tree01.jpgE551438F-166F-491C-AE90-13DCE18C6367Large.jpg"))
        self.picture2.setObjectName("picture2")
        self.lineEdit = QtWidgets.QLineEdit(add_feedback)
        self.lineEdit.setGeometry(QtCore.QRect(260, 240, 771, 51))
        self.lineEdit.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";\n""border-radius: 20;")
        self.lineEdit.setObjectName("lineEdit")
        self.name_surname = QtWidgets.QLabel(add_feedback)
        self.name_surname.setGeometry(QtCore.QRect(0, 230, 251, 71))
        self.name_surname.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";")
        self.name_surname.setObjectName("name_surname")
        self.lineEdit_2 = QtWidgets.QLineEdit(add_feedback)
        self.lineEdit_2.setGeometry(QtCore.QRect(260, 320, 771, 51))
        self.lineEdit_2.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";\n""border-radius: 20;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(add_feedback)
        self.lineEdit_3.setGeometry(QtCore.QRect(260, 410, 771, 51))
        self.lineEdit_3.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";\n""border-radius: 20;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.estimation = QtWidgets.QLabel(add_feedback)
        self.estimation.setGeometry(QtCore.QRect(10, 310, 251, 71))
        self.estimation.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";")
        self.estimation.setObjectName("estimation")
        self.comment = QtWidgets.QLabel(add_feedback)
        self.comment.setGeometry(QtCore.QRect(10, 400, 251, 71))
        self.comment.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";")
        self.comment.setObjectName("comment")
        self.warning_l = QtWidgets.QLabel(add_feedback)
        self.warning_l.setGeometry(QtCore.QRect(330, 580, 671, 71))
        self.warning_l.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";")
        self.warning_l.setObjectName("warning_l")
        self.add_feedback_btn = QtWidgets.QPushButton(add_feedback)
        self.add_feedback_btn.setGeometry(QtCore.QRect(240, 490, 811, 71))
        self.add_feedback_btn.setStyleSheet("QPushButton{\n""background-color: rgb(0, 85, 0);\n"
                                            "font: 63 20pt \"Yu Gothic UI Semibold\";\n""border-radius: 30;\n""}\n""\n"
                                            "QPushButton:pressed{\n""    background-color: rgb(200, 200, 200)\n""    \n"
                                            "}")
        self.add_feedback_btn.setObjectName("add_feedback_btn")

        self.green_l.raise_()
        self.mainl2.raise_()
        self.mainl.raise_()
        self.black_l.raise_()
        self.add_feedback_2.raise_()
        self.picture1.raise_()
        self.back_btn.raise_()
        self.picture2.raise_()
        self.lineEdit.raise_()
        self.name_surname.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        self.estimation.raise_()
        self.comment.raise_()
        self.warning_l.raise_()
        self.add_feedback_btn.raise_()
        self.retranslateUi(add_feedback)
        QtCore.QMetaObject.connectSlotsByName(add_feedback)

    def retranslateUi(self, add_feedback):
        _translate = QtCore.QCoreApplication.translate
        add_feedback.setWindowTitle(_translate("add_feedback", "Form"))
        self.back_btn.setText(_translate("add_feedback", "Назад"))
        self.mainl2.setText(_translate("add_feedback", "Кинотеатр для\n"
                                                       " всей семьи"))
        self.mainl.setToolTip(_translate("add_feedback", "<html><head/><body><p><span style=\" font-size:16pt;"
                                                         " color:#ffffff;\">WCinema</span></p></body></html>"))
        self.mainl.setWhatsThis(_translate("add_feedback", "<html><head/><body><p>ACinema</p></body></html>"))
        self.mainl.setText(_translate("add_feedback", "ACinema"))
        self.add_feedback_2.setText(_translate("add_feedback", "Добавить отзывы"))
        self.name_surname.setText(_translate("add_feedback", "Имя и Фамилия"))
        self.estimation.setText(_translate("add_feedback", "Оценка"))
        self.comment.setText(_translate("add_feedback", "Коментарий"))
        self.warning_l.setText(_translate("add_feedback", "Все строки обязательны к заполнению "))
        self.add_feedback_btn.setText(_translate("add_feedback", "Добавить отзыв"))
