from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Change_form(object):
    def setupUi(self, Change_form):
        Change_form.setObjectName("Change_form")
        Change_form.resize(1140, 850)
        self.green_l = QtWidgets.QLabel(Change_form)
        self.green_l.setGeometry(QtCore.QRect(0, 0, 1141, 81))
        self.green_l.setStyleSheet("background-color: rgb(0, 85, 0);")
        self.green_l.setText("")
        self.green_l.setObjectName("green_l")
        self.black_l = QtWidgets.QLabel(Change_form)
        self.black_l.setGeometry(QtCore.QRect(0, 80, 1141, 101))
        self.black_l.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.black_l.setText("")
        self.black_l.setObjectName("black_l")
        self.main_l1 = QtWidgets.QLabel(Change_form)
        self.main_l1.setGeometry(QtCore.QRect(0, 0, 161, 81))
        self.main_l1.setStyleSheet("background-color: rgb(0, 85, 0);\n""\n""font: 20pt \"Adobe Caslon Pro\";\n"
                                   "color: rgb(255, 255, 255);")
        self.main_l1.setObjectName("main_l1")
        self.back_btn = QtWidgets.QPushButton(Change_form)
        self.back_btn.setGeometry(QtCore.QRect(910, 90, 181, 71))
        self.back_btn.setStyleSheet("QPushButton{\n""background-color: rgb(255, 255, 255);\n"
                                    "font: 63 20pt \"Yu Gothic UI Semibold\";\n""border-radius: 30;\n""}\n""\n"
                                    "QPushButton:pressed{\n""    background-color: rgb(200, 200, 200)\n""    \n""}")
        self.back_btn.setObjectName("back_btn")
        self.main_l2 = QtWidgets.QLabel(Change_form)
        self.main_l2.setGeometry(QtCore.QRect(140, 10, 181, 61))
        self.main_l2.setStyleSheet("background-color: rgb(0, 85, 0);\n""color: rgb(217, 217, 217);")
        self.main_l2.setObjectName("main_l2")
        self.comboBox = QtWidgets.QComboBox(Change_form)
        self.comboBox.setGeometry(QtCore.QRect(600, 220, 101, 71))
        self.comboBox.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";\n""border-radius: 20;")
        self.comboBox.setObjectName("comboBox")
        self.title = QtWidgets.QLineEdit(Change_form)
        self.title.setGeometry(QtCore.QRect(190, 300, 811, 61))
        self.title.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";\n""border-radius: 20;")
        self.title.setObjectName("title")
        self.way = QtWidgets.QLineEdit(Change_form)
        self.way.setGeometry(QtCore.QRect(300, 380, 701, 61))
        self.way.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";\n""border-radius: 20;")
        self.way.setObjectName("way")
        self.first = QtWidgets.QLineEdit(Change_form)
        self.first.setGeometry(QtCore.QRect(250, 470, 251, 61))
        self.first.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";\n""border-radius: 20;")
        self.first.setObjectName("first")
        self.change_l = QtWidgets.QLabel(Change_form)
        self.change_l.setGeometry(QtCore.QRect(80, 220, 531, 51))
        self.change_l.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";\n""")
        self.change_l.setObjectName("change_l")
        self.name_l = QtWidgets.QLabel(Change_form)
        self.name_l.setGeometry(QtCore.QRect(30, 300, 151, 51))
        self.name_l.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";\n""")
        self.name_l.setObjectName("name_l")
        self.way_l = QtWidgets.QLabel(Change_form)
        self.way_l.setGeometry(QtCore.QRect(20, 380, 281, 51))
        self.way_l.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";\n""")
        self.way_l.setObjectName("way_l")
        self.first_l = QtWidgets.QLabel(Change_form)
        self.first_l.setGeometry(QtCore.QRect(30, 470, 221, 51))
        self.first_l.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";\n""")
        self.first_l.setObjectName("first_l")
        self.second_l = QtWidgets.QLabel(Change_form)
        self.second_l.setGeometry(QtCore.QRect(520, 470, 221, 51))
        self.second_l.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";\n""")
        self.second_l.setObjectName("second_l")
        self.list_of_place_l = QtWidgets.QLabel(Change_form)
        self.list_of_place_l.setGeometry(QtCore.QRect(40, 550, 381, 51))
        self.list_of_place_l.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";\n""")
        self.list_of_place_l.setObjectName("list_of_place_l")
        self.second = QtWidgets.QLineEdit(Change_form)
        self.second.setGeometry(QtCore.QRect(760, 470, 241, 61))
        self.second.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";\n""border-radius: 20;")
        self.second.setObjectName("second")
        self.list_of_places = QtWidgets.QLineEdit(Change_form)
        self.list_of_places.setGeometry(QtCore.QRect(430, 550, 571, 61))
        self.list_of_places.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";\n""border-radius: 20;")
        self.list_of_places.setObjectName("list_of_places")
        self.picture1 = QtWidgets.QLabel(Change_form)
        self.picture1.setGeometry(QtCore.QRect(-220, 640, 541, 511))
        self.picture1.setText("")
        self.picture1.setPixmap(QtGui.QPixmap("./pictures/oak_tree01.jpgE551438F-166F-491C-AE90-13DCE18C6367Large.jpg"))
        self.picture1.setObjectName("picture1")
        self.picture2 = QtWidgets.QLabel(Change_form)
        self.picture2.setGeometry(QtCore.QRect(810, 660, 541, 511))
        self.picture2.setText("")
        self.picture2.setPixmap(QtGui.QPixmap("./pictures/oak_tree01.jpgE551438F-166F-491C-AE90-13DCE18C6367Large.jpg"))
        self.picture2.setObjectName("picture2")
        self.back_btn_2 = QtWidgets.QPushButton(Change_form)
        self.back_btn_2.setGeometry(QtCore.QRect(320, 670, 491, 71))
        self.back_btn_2.setStyleSheet("QPushButton{\n""background-color: rgb(0, 85, 0);\n"
                                      "font: 63 20pt \"Yu Gothic UI Semibold\";\n""border-radius: 30;\n""}\n""\n"
                                      "QPushButton:pressed{\n""    background-color: rgb(200, 200, 200)\n""    \n""}")
        self.back_btn_2.setObjectName("back_btn_2")

        self.retranslateUi(Change_form)
        QtCore.QMetaObject.connectSlotsByName(Change_form)

    def retranslateUi(self, Change_form):
        _translate = QtCore.QCoreApplication.translate
        Change_form.setWindowTitle(_translate("Change_form", "Form"))
        self.main_l1.setText(_translate("Change_form", "ACinema"))
        self.back_btn.setText(_translate("Change_form", "Назад"))
        self.main_l2.setText(_translate("Change_form", "Кинотеатр для\n"" всей семьи"))
        self.change_l.setText(_translate("Change_form", "Выбирите какой фильм меняем"))
        self.name_l.setText(_translate("Change_form", "Название"))
        self.way_l.setText(_translate("Change_form", "Путь на картинку"))
        self.first_l.setText(_translate("Change_form", "Првый сеанс"))
        self.second_l.setText(_translate("Change_form", "Второй сеанс"))
        self.list_of_place_l.setText(_translate("Change_form", "Список купленных мест"))
        self.back_btn_2.setText(_translate("Change_form", "Сохранить"))
