from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Contacts_form(object):
    def setupUi(self, Contacts_form):
        Contacts_form.setObjectName("Contacts_form")
        Contacts_form.resize(1140, 850)
        self.green_l = QtWidgets.QLabel(Contacts_form)
        self.green_l.setGeometry(QtCore.QRect(0, 0, 1141, 81))
        self.green_l.setStyleSheet("background-color: rgb(0, 85, 0);")
        self.green_l.setText("")
        self.green_l.setObjectName("green_l")
        self.black_l = QtWidgets.QLabel(Contacts_form)
        self.black_l.setGeometry(QtCore.QRect(0, 80, 1141, 101))
        self.black_l.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.black_l.setText("")
        self.black_l.setObjectName("black_l")
        self.main_l1 = QtWidgets.QLabel(Contacts_form)
        self.main_l1.setGeometry(QtCore.QRect(0, 0, 161, 81))
        self.main_l1.setStyleSheet("background-color: rgb(0, 85, 0);\n""\n""font: 20pt \"Adobe Caslon Pro\";\n"
                                   "color: rgb(255, 255, 255);")
        self.main_l1.setObjectName("main_l1")
        self.back_btn = QtWidgets.QPushButton(Contacts_form)
        self.back_btn.setGeometry(QtCore.QRect(910, 90, 181, 71))
        self.back_btn.setStyleSheet("QPushButton{\n""background-color: rgb(255, 255, 255);\n"
                                    "font: 63 20pt \"Yu Gothic UI Semibold\";\n""border-radius: 30;\n""}\n""\n"
                                    "QPushButton:pressed{\n""    background-color: rgb(200, 200, 200)\n""    \n""}")
        self.back_btn.setObjectName("back_btn")
        self.main_l2 = QtWidgets.QLabel(Contacts_form)
        self.main_l2.setGeometry(QtCore.QRect(140, 10, 181, 61))
        self.main_l2.setStyleSheet("background-color: rgb(0, 85, 0);\n""color: rgb(217, 217, 217);")
        self.main_l2.setObjectName("main_l2")
        self.picture2 = QtWidgets.QLabel(Contacts_form)
        self.picture2.setGeometry(QtCore.QRect(800, 590, 561, 491))
        self.picture2.setText("")
        self.picture2.setPixmap(QtGui.QPixmap("./pictures/oak_tree01.jpgE551438F-166F-491C-AE90-13DCE18C6367Large.jpg"))
        self.picture2.setObjectName("picture2")
        self.picture1 = QtWidgets.QLabel(Contacts_form)
        self.picture1.setGeometry(QtCore.QRect(-260, 570, 561, 491))
        self.picture1.setText("")
        self.picture1.setPixmap(QtGui.QPixmap("./pictures/oak_tree01.jpgE551438F-166F-491C-AE90-13DCE18C6367Large.jpg"))
        self.picture1.setObjectName("picture1")
        self.link1 = QtWidgets.QLabel(Contacts_form)
        self.link1.setGeometry(QtCore.QRect(190, 310, 401, 91))
        self.link1.setStyleSheet("font: 20pt \"Adobe Caslon Pro\";")
        self.link1.setObjectName("link1")
        self.phone = QtWidgets.QLabel(Contacts_form)
        self.phone.setGeometry(QtCore.QRect(10, 220, 391, 71))
        self.phone.setStyleSheet("font: 20pt \"Adobe Caslon Pro\";")
        self.phone.setObjectName("phone")
        self.line = QtWidgets.QFrame(Contacts_form)
        self.line.setGeometry(QtCore.QRect(0, 210, 1131, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Contacts_form)
        self.line_2.setGeometry(QtCore.QRect(0, 290, 1141, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.instagram = QtWidgets.QLabel(Contacts_form)
        self.instagram.setGeometry(QtCore.QRect(30, 320, 171, 61))
        self.instagram.setStyleSheet("font: 20pt \"Adobe Caslon Pro\";")
        self.instagram.setObjectName("instagram")
        self.line_3 = QtWidgets.QFrame(Contacts_form)
        self.line_3.setGeometry(QtCore.QRect(-40, 380, 1251, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.telegram = QtWidgets.QLabel(Contacts_form)
        self.telegram.setGeometry(QtCore.QRect(30, 400, 171, 61))
        self.telegram.setStyleSheet("font: 20pt \"Adobe Caslon Pro\";")
        self.telegram.setObjectName("telegram")
        self.link2 = QtWidgets.QLabel(Contacts_form)
        self.link2.setGeometry(QtCore.QRect(190, 390, 401, 91))
        self.link2.setStyleSheet("font: 20pt \"Adobe Caslon Pro\";")
        self.link2.setObjectName("link2")

        self.retranslateUi(Contacts_form)
        QtCore.QMetaObject.connectSlotsByName(Contacts_form)

    def retranslateUi(self, Contacts_form):
        _translate = QtCore.QCoreApplication.translate
        Contacts_form.setWindowTitle(_translate("Contacts_form", "Form"))
        self.main_l1.setText(_translate("Contacts_form", "ACinema"))
        self.back_btn.setText(_translate("Contacts_form", "Назад"))
        self.main_l2.setText(_translate("Contacts_form", "Кинотеатр для\n"" всей семьи"))
        self.link1.setText(_translate("Contacts_form", "<a href=\"https://www.instagram.com/\">"
                                                       "  https://www.instagram.com</a>"))
        self.phone.setText(_translate("Contacts_form", "Телефон:    +79196071790"))
        self.instagram.setText(_translate("Contacts_form", "Instagram"))
        self.telegram.setText(_translate("Contacts_form", "Telegram"))
        self.link2.setText(_translate("Contacts_form", "<a href=\"https://web.telegram.org"
                                                       "/k/#-1607052528\">  https://www.telegram.org </a>"))
