from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_discounts_form(object):
    def setupUi(self, discounts_form):
        discounts_form.setObjectName("discounts_form")
        discounts_form.resize(1140, 857)
        self.green_l = QtWidgets.QLabel(discounts_form)
        self.green_l.setGeometry(QtCore.QRect(0, 0, 1141, 81))
        self.green_l.setStyleSheet("background-color: rgb(0, 85, 0);")
        self.green_l.setText("")
        self.green_l.setObjectName("green_l")
        self.main_l = QtWidgets.QLabel(discounts_form)
        self.main_l.setGeometry(QtCore.QRect(20, 10, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe Caslon Pro")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.main_l.setFont(font)
        self.main_l.setStyleSheet("background-color: rgb(0, 85, 0);\n""\n""font: 20pt \"Adobe Caslon Pro\";\n"
                                  "color: rgb(255, 255, 255);")
        self.main_l.setObjectName("main_l")
        self.main_l2 = QtWidgets.QLabel(discounts_form)
        self.main_l2.setGeometry(QtCore.QRect(180, 10, 201, 61))
        self.main_l2.setMaximumSize(QtCore.QSize(201, 16777215))
        font = QtGui.QFont()
        font.setFamily("Adobe Caslon Pro")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.main_l2.setFont(font)
        self.main_l2.setStyleSheet("background-color: rgb(0, 85, 0);\n""color: rgb(217, 217, 217);")
        self.main_l2.setObjectName("main_l2")
        self.big_l = QtWidgets.QLabel(discounts_form)
        self.big_l.setGeometry(QtCore.QRect(330, 40, 411, 131))
        self.big_l.setStyleSheet("font: 63 80pt \"Yu Gothic UI Semibold\";\n""color: rgb(255, 255, 255);\n""")
        self.big_l.setObjectName("big_l")
        self.black_line = QtWidgets.QLabel(discounts_form)
        self.black_line.setGeometry(QtCore.QRect(0, 80, 1141, 101))
        self.black_line.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.black_line.setText("")
        self.black_line.setObjectName("black_line")
        self.back_btn = QtWidgets.QPushButton(discounts_form)
        self.back_btn.setGeometry(QtCore.QRect(940, 90, 181, 71))
        self.back_btn.setStyleSheet("QPushButton{\n""background-color: rgb(255, 255, 255);\n"
                                    "font: 63 20pt \"Yu Gothic UI Semibold\";\n""border-radius: 30;\n""}\n""\n"
                                    "QPushButton:pressed{\n""    background-color: rgb(200, 200, 200)\n""    \n""}")
        self.back_btn.setObjectName("back_btn")
        self.discount1 = QtWidgets.QLabel(discounts_form)
        self.discount1.setGeometry(QtCore.QRect(70, 220, 1051, 141))
        self.discount1.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";")
        self.discount1.setObjectName("discount1")
        self.discount2 = QtWidgets.QLabel(discounts_form)
        self.discount2.setGeometry(QtCore.QRect(70, 310, 691, 121))
        self.discount2.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";")
        self.discount2.setObjectName("discount2")
        self.line = QtWidgets.QFrame(discounts_form)
        self.line.setGeometry(QtCore.QRect(-90, 580, 1321, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(discounts_form)
        self.line_2.setGeometry(QtCore.QRect(-50, 410, 1321, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(discounts_form)
        self.line_3.setGeometry(QtCore.QRect(-90, 320, 1321, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.warning_l = QtWidgets.QLabel(discounts_form)
        self.warning_l.setEnabled(True)
        self.warning_l.setGeometry(QtCore.QRect(180, 580, 771, 131))
        self.warning_l.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";\n""color: rgb(170, 0, 0);")
        self.warning_l.setObjectName("warning_l")
        self.discount3 = QtWidgets.QLabel(discounts_form)
        self.discount3.setGeometry(QtCore.QRect(60, 440, 1071, 131))
        self.discount3.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";")
        self.discount3.setObjectName("discount3")
        self.label_10 = QtWidgets.QLabel(discounts_form)
        self.label_10.setGeometry(QtCore.QRect(810, 660, 551, 511))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("./pictures/oak_tree01.jpgE551438F-166F-491C-AE90-13DCE18C6367Large.jpg"))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(discounts_form)
        self.label_11.setGeometry(QtCore.QRect(-240, 630, 551, 511))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("./pictures/oak_tree01.jpgE551438F-166F-491C-AE90-13DCE18C6367Large.jpg"))
        self.label_11.setObjectName("label_11")
        self.label_11.raise_()
        self.label_10.raise_()
        self.green_l.raise_()
        self.main_l.raise_()
        self.main_l2.raise_()
        self.black_line.raise_()
        self.back_btn.raise_()
        self.discount1.raise_()
        self.discount2.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.warning_l.raise_()
        self.discount3.raise_()
        self.big_l.raise_()

        self.retranslateUi(discounts_form)
        QtCore.QMetaObject.connectSlotsByName(discounts_form)

    def retranslateUi(self, discounts_form):
        _translate = QtCore.QCoreApplication.translate
        discounts_form.setWindowTitle(_translate("discounts_form", "Form"))
        self.main_l.setToolTip(_translate("discounts_form", "<html><head/><body><p><span style=\" font-size:16pt;"
                                                            " color:#ffffff;\">WCinema</span></p></body></html>"))
        self.main_l.setWhatsThis(_translate("discounts_form", "<html><head/><body><p>ACinema</p></body></html>"))
        self.main_l.setText(_translate("discounts_form", "ACinema"))
        self.main_l2.setText(_translate("discounts_form", "Кинотеатр для\n"" всей семьи"))
        self.big_l.setText(_translate("discounts_form", "Акции"))
        self.back_btn.setText(_translate("discounts_form", "Назад"))
        self.discount1.setText(_translate("discounts_form", "1) Детям до 3-х лет (включительно) – просмотр бесплатно "
                                                            "\n""(без очков и посадочного места).\n"""))
        self.discount2.setText(_translate("discounts_form", "2) В день рождения просмотр бесплатный"))
        self.warning_l.setText(_translate("discounts_form", "Все скидки предоставляются при предъявлении\n"
                                                            " соответствующих документов."))
        self.discount3.setText(_translate("discounts_form", "3)Для МНОГОДЕТНЫХ СЕМЕЙ действует скидка 30%\n"
                                                            " на все сеансы и форматы при посещение ТРЁХ \n"
                                                            "членов семьи и более единовременно на один сеанс. "))
