from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3


def start():
        con = sqlite3.connect(r'.\rev.db')
        cur = con.cursor()
        result = cur.execute('''SELECT title, way FROM actual_films''').fetchall()
        return result


class Ui_main_form(object):
    def setupUi(self, main_form):
        main_form.setObjectName("main_form")
        main_form.resize(1140, 850)
        self.green_label = QtWidgets.QLabel(main_form)
        self.green_label.setGeometry(QtCore.QRect(0, -10, 1151, 101))
        self.green_label.setStyleSheet("background-color: rgb(0, 85, 0);")
        self.green_label.setText("")
        self.green_label.setObjectName("green_label")
        self.label_of_cinema = QtWidgets.QLabel(main_form)
        self.label_of_cinema.setGeometry(QtCore.QRect(10, 20, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe Caslon Pro")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_of_cinema.setFont(font)
        self.label_of_cinema.setStyleSheet("background-color: rgb(0, 85, 0);\n""\n""font:"
                                           " 20pt \"Adobe Caslon Pro\";\n""color: rgb(255, 255, 255);")
        self.label_of_cinema.setObjectName("label_of_cinema")
        self.label_of_cinema_2 = QtWidgets.QLabel(main_form)
        self.label_of_cinema_2.setGeometry(QtCore.QRect(160, 20, 201, 61))
        self.label_of_cinema_2.setMaximumSize(QtCore.QSize(201, 16777215))
        font = QtGui.QFont()
        font.setFamily("Adobe Caslon Pro")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_of_cinema_2.setFont(font)
        self.label_of_cinema_2.setStyleSheet("background-color: rgb(0, 85, 0);\n""color: rgb(217, 217, 217);")
        self.label_of_cinema_2.setObjectName("label_of_cinema_2")
        self.chose_sians = QtWidgets.QPushButton(main_form)
        self.chose_sians.setGeometry(QtCore.QRect(20, 100, 251, 81))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.chose_sians.setFont(font)
        self.chose_sians.setStyleSheet("QPushButton{\n""background-color: rgb(0, 170, 0);\n"
                                       "font: 63 20pt \"Yu Gothic UI Semibold\";\n""border-radius: 30;\n"
                                       "}\n""\n""QPushButton:pressed{\n""    background-color: rgb(85, 255, 0)\n"
                                       "}\n""")
        self.chose_sians.setObjectName("chose_sians")
        self.blac_label = QtWidgets.QLabel(main_form)
        self.blac_label.setGeometry(QtCore.QRect(0, 90, 1141, 101))
        self.blac_label.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.blac_label.setText("")
        self.blac_label.setObjectName("blac_label")
        self.contacts = QtWidgets.QPushButton(main_form)
        self.contacts.setGeometry(QtCore.QRect(290, 110, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.contacts.setFont(font)
        self.contacts.setStyleSheet("QPushButton{\n""background-color: rgb(255, 255, 255);\n"
                                    "font: 63 20pt \"Yu Gothic UI Semibold\";\n""border-radius: 30;\n"
                                    "}\n""\n""QPushButton:pressed{\n"
                                    "    background-color: rgb(200, 200, 200)\n""    \n""}")
        self.contacts.setObjectName("contacts")
        self.actious = QtWidgets.QPushButton(main_form)
        self.actious.setGeometry(QtCore.QRect(490, 110, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.actious.setFont(font)
        self.actious.setStyleSheet("QPushButton{\n""background-color: rgb(255, 255, 255);\n"
                                   "font: 63 20pt \"Yu Gothic UI Semibold\";\n""border-radius: 30;\n""}\n"
                                   "\n""QPushButton:pressed{\n""    background-color: rgb(200, 200, 200)\n""    \n""}")
        self.actious.setObjectName("actious")
        self.about_complex = QtWidgets.QPushButton(main_form)
        self.about_complex.setGeometry(QtCore.QRect(700, 110, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.about_complex.setFont(font)
        self.about_complex.setStyleSheet("QPushButton{\n""background-color: rgb(255, 255, 255);\n"
                                         "font: 63 20pt \"Yu Gothic UI Semibold\";\n""border-radius: 30;\n"
                                         "}\n""\n""QPushButton:pressed{\n"" "
                                         "   background-color: rgb(200, 200, 200)\n""    \n""}")
        self.about_complex.setObjectName("about_complex")
        self.change_actual = QtWidgets.QPushButton(main_form)
        self.change_actual.setGeometry(QtCore.QRect(410, 10, 391, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.change_actual.setFont(font)
        self.change_actual.setStyleSheet("QPushButton{\n""background-color: rgb(255, 255, 255);\n"
                                         "font: 63 20pt \"Yu Gothic UI Semibold\";\n""border-radius: 30;\n"
                                         "}\n""\n""QPushButton:pressed{\n"""
                                         "    background-color: rgb(200, 200, 200)\n""    \n""}")
        self.change_actual.setObjectName("change_actual")
        self.line = QtWidgets.QFrame(main_form)
        self.line.setGeometry(QtCore.QRect(0, 210, 1141, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.actual = QtWidgets.QLabel(main_form)
        self.actual.setGeometry(QtCore.QRect(10, 230, 301, 61))
        self.actual.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";\n""border-radius: 30;\n""")
        self.actual.setObjectName("actual")
        self.line_2 = QtWidgets.QFrame(main_form)
        self.line_2.setGeometry(QtCore.QRect(0, 290, 1131, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.avatar = QtWidgets.QPushButton(main_form)
        self.avatar.setGeometry(QtCore.QRect(0, 570, 311, 61))
        self.avatar.setStyleSheet("QPushButton{\n""background-color: rgb(0, 170, 0);\n"
                                  "font: 63 20pt \"Yu Gothic UI Semibold\";\n""border-radius: 30;\n""}\n""\n"
                                  "QPushButton:pressed{\n""    background-color: rgb(85, 255, 0)\n""}")

        self.picture = QtWidgets.QLabel(main_form)
        self.picture.setGeometry(QtCore.QRect(-260, 650, 551, 481))
        self.picture.setText("")
        self.picture.setPixmap(QtGui.QPixmap("./pictures/oak_tree01.jpgE551438F-166F-491C-AE90-13DCE18C6367Large.jpg"))
        self.picture.setObjectName("picture")
        self.heard = QtWidgets.QPushButton(main_form)
        self.heard.setGeometry(QtCore.QRect(330, 570, 481, 61))
        self.heard.setStyleSheet("QPushButton{\n""background-color: rgb(0, 170, 0);\n"""
                                 "font: 63 20pt \"Yu Gothic UI Semibold\";\n"
                                 "border-radius: 30;\n""}\n""\n""QPushButton:pressed{\n"""
                                 "    background-color: rgb(85, 255, 0)\n""}")
        self.heard.setObjectName("heard")
        self.make_reviews = QtWidgets.QPushButton(main_form)
        self.make_reviews.setGeometry(QtCore.QRect(350, 770, 511, 61))
        self.make_reviews.setStyleSheet("QPushButton{\n""background-color: rgb(0, 170, 0);\n"
                                        "font: 63 20pt \"Yu Gothic UI Semibold\";\n""border-radius: 30;\n"
                                        "}\n""\n""QPushButton:pressed{\n""    background-color: rgb(85, 255, 0)\n""}")
        self.make_reviews.setObjectName("make_reviews")
        self.pictureAdam = QtWidgets.QLabel(main_form)
        self.pictureAdam.setGeometry(QtCore.QRect(840, 310, 291, 321))
        self.pictureAdam.setText("")

        self.pictureAdam.setScaledContents(True)
        self.pictureAdam.setObjectName("pictureAdam")
        self.adam = QtWidgets.QPushButton(main_form)
        self.adam.setGeometry(QtCore.QRect(840, 570, 291, 61))
        self.adam.setStyleSheet("QPushButton{\n""background-color: rgb(0, 170, 0);\n"
                                "font: 63 20pt \"Yu Gothic UI Semibold\";\n""border-radius: 30;\n""}\n"
                                "\n""QPushButton:pressed{\n""    background-color: rgb(85, 255, 0)\n""}")
        self.adam.setObjectName("adam")
        self.line_3 = QtWidgets.QFrame(main_form)
        self.line_3.setGeometry(QtCore.QRect(310, 210, 1151, 16))
        self.line_3.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(main_form)
        self.line_4.setGeometry(QtCore.QRect(-10, 630, 1151, 16))
        self.line_4.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_6 = QtWidgets.QFrame(main_form)
        self.line_6.setGeometry(QtCore.QRect(310, 300, 20, 341))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(main_form)
        self.line_7.setGeometry(QtCore.QRect(810, 290, 20, 341))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.picture2 = QtWidgets.QLabel(main_form)
        self.picture2.setGeometry(QtCore.QRect(900, 630, 551, 481))
        self.picture2.setText("")
        self.picture2.setPixmap(QtGui.QPixmap("./pictures/oak_tree01.jpgE551438F-166F-491C-AE90-13DCE18C6367Large.jpg"))
        self.picture2.setObjectName("picture2")
        self.label = QtWidgets.QLabel(main_form)
        self.label.setGeometry(QtCore.QRect(10, 310, 301, 311))
        self.label.setText("")

        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(main_form)
        self.label_2.setGeometry(QtCore.QRect(340, 310, 461, 321))
        self.label_2.setText("")
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.label.raise_()
        self.green_label.raise_()
        self.label_of_cinema.raise_()
        self.label_of_cinema_2.raise_()
        self.blac_label.raise_()
        self.chose_sians.raise_()
        self.contacts.raise_()
        self.actious.raise_()
        self.about_complex.raise_()
        self.change_actual.raise_()
        self.line.raise_()
        self.actual.raise_()
        self.line_2.raise_()
        self.avatar.raise_()
        self.picture.raise_()
        self.heard.raise_()
        self.make_reviews.raise_()
        self.pictureAdam.raise_()
        self.adam.raise_()
        self.line_3.raise_()
        self.line_6.raise_()
        self.line_7.raise_()
        self.picture2.raise_()
        self.line_4.raise_()

        self.retranslateUi(main_form)
        QtCore.QMetaObject.connectSlotsByName(main_form)

    def retranslateUi(self, main_form):

        _translate = QtCore.QCoreApplication.translate
        main_form.setWindowTitle(_translate("main_form", "Form"))
        self.label_of_cinema.setToolTip(_translate("main_form", "<html><head/><body><p><span style=\" font-size:16pt;"
                                                                " color:#ffffff;\">WCinema</span></p></body></html>"))
        self.label_of_cinema.setWhatsThis(_translate("main_form", "<html><head/><body><p>ACinema</p></body></html>"))
        self.label_of_cinema.setText(_translate("main_form", "ACinema"))
        self.label_of_cinema_2.setText(_translate("main_form", "Кинотеатр для\n"" всей семьи"))
        self.chose_sians.setText(_translate("main_form", "Выбрать Сеанс"))
        self.contacts.setText(_translate("main_form", "Контакты"))
        self.actious.setText(_translate("main_form", "Акции"))
        self.about_complex.setText(_translate("main_form", "О комплексе"))
        self.change_actual.setText(_translate("main_form", "Сменить Актуальные"))
        self.actual.setText(_translate("main_form", "Актуально сейчас:"))
        self.make_reviews.setText(_translate("main_form", "Оставить отзыв"))
