from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pay_form(object):
    def setupUi(self, pay_form):
        pay_form.setObjectName("pay_form")
        pay_form.resize(1140, 850)
        self.green_l = QtWidgets.QLabel(pay_form)
        self.green_l.setGeometry(QtCore.QRect(0, 0, 1141, 81))
        self.green_l.setStyleSheet("background-color: rgb(0, 85, 0);")
        self.green_l.setText("")
        self.green_l.setObjectName("green_l")
        self.black_l = QtWidgets.QLabel(pay_form)
        self.black_l.setGeometry(QtCore.QRect(0, 80, 1141, 101))
        self.black_l.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.black_l.setText("")
        self.black_l.setObjectName("black_l")
        self.back_btn = QtWidgets.QPushButton(pay_form)
        self.back_btn.setGeometry(QtCore.QRect(920, 100, 181, 71))
        self.back_btn.setStyleSheet("QPushButton{\n""background-color: rgb(255, 255, 255);\n"
                                    "font: 63 20pt \"Yu Gothic UI Semibold\";\n""border-radius: 30;\n"
                                    "}\n""\n""QPushButton:pressed{\n"
                                    "    background-color: rgb(200, 200, 200)\n""    \n""}")
        self.back_btn.setObjectName("back_btn")
        self.main_l = QtWidgets.QLabel(pay_form)
        self.main_l.setGeometry(QtCore.QRect(10, 10, 161, 61))
        self.main_l.setStyleSheet("background-color: rgb(0, 85, 0);\n""\n"
                                  "font: 20pt \"Adobe Caslon Pro\";\n""color: rgb(255, 255, 255);")
        self.main_l.setObjectName("main_l")
        self.main_l2 = QtWidgets.QLabel(pay_form)
        self.main_l2.setGeometry(QtCore.QRect(150, 0, 181, 71))
        self.main_l2.setStyleSheet("background-color: rgb(0, 85, 0);\n""color: rgb(217, 217, 217);")
        self.main_l2.setObjectName("main_l2")
        self.cart_n_l = QtWidgets.QLabel(pay_form)
        self.cart_n_l.setGeometry(QtCore.QRect(30, 190, 221, 71))
        self.cart_n_l.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";\n""")
        self.cart_n_l.setObjectName("cart_n_l")
        self.cart_n = QtWidgets.QLineEdit(pay_form)
        self.cart_n.setGeometry(QtCore.QRect(20, 270, 641, 61))
        self.cart_n.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";\n""border-radius: 30;\n""")
        self.cart_n.setObjectName("cart_n")
        self.name_surn_l = QtWidgets.QLabel(pay_form)
        self.name_surn_l.setGeometry(QtCore.QRect(30, 340, 281, 71))
        self.name_surn_l.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";\n""")
        self.name_surn_l.setObjectName("name_surn_l")
        self.name_surname = QtWidgets.QLineEdit(pay_form)
        self.name_surname.setGeometry(QtCore.QRect(20, 410, 641, 61))
        self.name_surname.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";\n""border-radius: 30;\n""")
        self.name_surname.setObjectName("name_surname")
        self.work_before_l = QtWidgets.QLabel(pay_form)
        self.work_before_l.setGeometry(QtCore.QRect(30, 480, 281, 71))
        self.work_before_l.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";\n""")
        self.work_before_l.setObjectName("work_before_l")
        self.work_before = QtWidgets.QLineEdit(pay_form)
        self.work_before.setGeometry(QtCore.QRect(30, 560, 191, 51))
        self.work_before.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";\n""border-radius: 20;\n""")
        self.work_before.setObjectName("work_before")
        self.cvc_l = QtWidgets.QLabel(pay_form)
        self.cvc_l.setGeometry(QtCore.QRect(410, 480, 81, 71))
        self.cvc_l.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";\n""")
        self.cvc_l.setObjectName("cvc_l")
        self.cvs = QtWidgets.QLineEdit(pay_form)
        self.cvs.setGeometry(QtCore.QRect(370, 560, 201, 51))
        self.cvs.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";\n""border-radius: 20;\n""")
        self.cvs.setObjectName("cvs")
        self.pay = QtWidgets.QPushButton(pay_form)
        self.pay.setGeometry(QtCore.QRect(40, 660, 571, 71))
        self.pay.setStyleSheet("QPushButton{\n""background-color: rgb(0, 85, 0);\n"
                               "font: 63 20pt \"Yu Gothic UI Semibold\";\n"
                               "border-radius: 30;\n""}\n""\n""QPushButton:pressed{\n"
                               "    background-color: rgb(200, 200, 200)\n""    \n""}")
        self.pay.setObjectName("pay")
        self.picture = QtWidgets.QLabel(pay_form)
        self.picture.setGeometry(QtCore.QRect(780, 580, 481, 481))
        self.picture.setText("")
        self.picture.setPixmap(QtGui.QPixmap("./oak_tree01.jpgE551438F-166F-491C-AE90-13DCE18C6367Large.jpg"))
        self.picture.setObjectName("picture")
        self.place = QtWidgets.QLabel(pay_form)
        self.place.setGeometry(QtCore.QRect(810, 380, 111, 71))
        self.place.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";\n""")
        self.place.setObjectName("place")
        self.row = QtWidgets.QLabel(pay_form)
        self.row.setGeometry(QtCore.QRect(810, 320, 91, 71))
        self.row.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";\n""")
        self.row.setObjectName("row")
        self.total = QtWidgets.QLabel(pay_form)
        self.total.setGeometry(QtCore.QRect(810, 270, 131, 71))
        self.total.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";\n""")
        self.total.setObjectName("total")
        self.for_pay = QtWidgets.QLabel(pay_form)
        self.for_pay.setGeometry(QtCore.QRect(810, 210, 221, 71))
        self.for_pay.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";\n""")
        self.for_pay.setObjectName("for_pay")
        self.col = QtWidgets.QLabel(pay_form)
        self.col.setGeometry(QtCore.QRect(940, 380, 51, 71))
        self.col.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";\n""")
        self.col.setObjectName("col")
        self.row_2 = QtWidgets.QLabel(pay_form)
        self.row_2.setGeometry(QtCore.QRect(940, 330, 51, 71))
        self.row_2.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";\n""")
        self.row_2.setObjectName("row_2")

        self.retranslateUi(pay_form)
        QtCore.QMetaObject.connectSlotsByName(pay_form)

    def retranslateUi(self, pay_form):
        _translate = QtCore.QCoreApplication.translate
        pay_form.setWindowTitle(_translate("pay_form", "Form"))
        self.back_btn.setText(_translate("pay_form", "Назад"))
        self.main_l.setText(_translate("pay_form", "ACinema"))
        self.main_l2.setText(_translate("pay_form", "Кинотеатр для\n"" всей семьи"))
        self.cart_n_l.setText(_translate("pay_form", "Номер карты"))
        self.name_surn_l.setText(_translate("pay_form", "Имя и Фамилия"))
        self.work_before_l.setText(_translate("pay_form", "Действительна до"))
        self.cvc_l.setText(_translate("pay_form", "CVC"))
        self.pay.setText(_translate("pay_form", "Оплатить"))
        self.place.setText(_translate("pay_form", "Место:"))
        self.row.setText(_translate("pay_form", "Ряд:"))
        self.total.setText(_translate("pay_form", "150 руб"))
        self.for_pay.setText(_translate("pay_form", "К оплате:"))
        self.col.setText(_translate("pay_form", "1"))
        self.row_2.setText(_translate("pay_form", "1"))
