from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_start_window(object):
    def setupUi(self, start_window):
        start_window.setObjectName("start_window")
        start_window.resize(1072, 771)
        self.centralwidget = QtWidgets.QWidget(start_window)
        self.centralwidget.setObjectName("centralwidget")
        self.green_label = QtWidgets.QLabel(self.centralwidget)
        self.green_label.setGeometry(QtCore.QRect(-80, 0, 1151, 101))
        self.green_label.setStyleSheet("background-color: rgb(0, 85, 0);")
        self.green_label.setText("")
        self.green_label.setObjectName("green_label")
        self.label_of_cinema = QtWidgets.QLabel(self.centralwidget)
        self.label_of_cinema.setGeometry(QtCore.QRect(20, 30, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe Caslon Pro")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_of_cinema.setFont(font)
        self.label_of_cinema.setStyleSheet("background-color: rgb(0, 85, 0);\n""\n""font: 20pt \"Adobe Caslon Pro\";\n"
                                           "color: rgb(255, 255, 255);")
        self.label_of_cinema.setObjectName("label_of_cinema")
        self.label_of_cinema_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_of_cinema_2.setGeometry(QtCore.QRect(180, 30, 201, 61))
        self.label_of_cinema_2.setMaximumSize(QtCore.QSize(201, 16777215))
        font = QtGui.QFont()
        font.setFamily("Adobe Caslon Pro")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_of_cinema_2.setFont(font)
        self.label_of_cinema_2.setStyleSheet("background-color: rgb(0, 85, 0);\n""color: rgb(217, 217, 217);")
        self.label_of_cinema_2.setObjectName("label_of_cinema_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(350, 80, 321, 171))
        self.label.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";")
        self.label.setObjectName("label")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(360, 370, 341, 101))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.start.setFont(font)
        self.start.setStyleSheet("QPushButton{\n""background-color: rgb(0, 170, 0);\n"
                                 "font: 63 20pt \"Yu Gothic UI Semibold\";\n""border-radius: 30;\n""}\n""\n"
                                 "QPushButton:pressed{\n""    background-color: rgb(85, 255, 0)\n""}\n""")
        self.start.setObjectName("start")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 190, 1071, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 120, 1071, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.picture1 = QtWidgets.QLabel(self.centralwidget)
        self.picture1.setGeometry(QtCore.QRect(-10, 210, 341, 381))
        self.picture1.setText("")
        self.picture1.setPixmap(QtGui.QPixmap("./pictures/10.jpg"))
        self.picture1.setScaledContents(True)
        self.picture1.setObjectName("picture1")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 610, 1071, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.picture2 = QtWidgets.QLabel(self.centralwidget)
        self.picture2.setGeometry(QtCore.QRect(740, 210, 321, 391))
        self.picture2.setText("")
        self.picture2.setPixmap(QtGui.QPixmap("./pictures/2.jpg"))
        self.picture2.setScaledContents(True)
        self.picture2.setObjectName("picture2")
        start_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(start_window)
        QtCore.QMetaObject.connectSlotsByName(start_window)

    def retranslateUi(self, start_window):
        _translate = QtCore.QCoreApplication.translate
        start_window.setWindowTitle(_translate("start_window", "MainWindow"))
        self.label_of_cinema.setToolTip(_translate("start_window", "<html><head/><body><p><span "
                                                                   "style=\" font-size:16pt"
                                                                   ";"" color:#ffffff;"
                                                                   "\">WCinema</span></p></body></html>"))
        self.label_of_cinema.setWhatsThis(_translate("start_window", "<html><head/><body><p>ACinema</p></body></html>"))
        self.label_of_cinema.setText(_translate("start_window", "ACinema"))
        self.label_of_cinema_2.setText(_translate("start_window", "Кинотеатр для\n"" всей семьи"))
        self.label.setText(_translate("start_window", "Добро пожаловать!"))
        self.start.setText(_translate("start_window", "Начнем"))
